/* AUTO-GENERATED by scripts/plugin-index.mjs — do not edit. */
import type { PluginFactory } from './discovery.js';
import { createMineclawMinecraftSystemPlugin } from '../plugins/builtin/minecraft-system/index.js';

/** Static factory mapping (build-generated; runtime never dynamic-imports). */
export const BUILTIN_PLUGIN_FACTORIES: ReadonlyMap<string, PluginFactory> = new Map([
  ['plugins/builtin/mineclaw.minecraft-system', createMineclawMinecraftSystemPlugin()],
]);