/* AUTO-GENERATED by scripts/plugin-index.mjs — do not edit. */
import type { PluginFactory } from './discovery.js';
import { createMineclawAgriculturePlugin } from '../plugins/builtin/agriculture/index.js';
import { createMineclawFollowPlugin } from '../plugins/builtin/follow/index.js';
import { createMineclawInventoryPlugin } from '../plugins/builtin/inventory/index.js';
import { createMineclawMinecraftPresencePlugin } from '../plugins/builtin/minecraft-presence/index.js';
import { createMineclawMinecraftSystemPlugin } from '../plugins/builtin/minecraft-system/index.js';
import { createMineclawStorageSystemPlugin } from '../plugins/builtin/storage-system/index.js';

/** Static factory mapping (build-generated; runtime never dynamic-imports). */
export const BUILTIN_PLUGIN_FACTORIES: ReadonlyMap<string, PluginFactory> = new Map([
  ['plugins/builtin/mineclaw.agriculture', createMineclawAgriculturePlugin()],
  ['plugins/builtin/mineclaw.follow', createMineclawFollowPlugin()],
  ['plugins/builtin/mineclaw.inventory', createMineclawInventoryPlugin()],
  ['plugins/builtin/mineclaw.minecraft-presence', createMineclawMinecraftPresencePlugin()],
  ['plugins/builtin/mineclaw.minecraft-system', createMineclawMinecraftSystemPlugin()],
  ['plugins/builtin/mineclaw.storage-system', createMineclawStorageSystemPlugin()],
]);